### ISSUE TITLE
Hybrid app, Flutter and Natives

### ISSUE THREAD

**Issue by KazuCocoa** [KazuCocoa/my_flutter_app2#1]
- Can handle flutter layer and Native layer via one test scenario?
- Is it helpful to support Appium Flutter Driver (for example) to take care the use-case?
- EarlGrey/XCUITest, Espresso, Detox, flutter_driver

**Comment by KazuCocoa** [comment]
Bellow error happens when I tried to run on espresso driver.
I need to take a look at the reason digging into instrumentation x flutter combination further.

```
$ ruby test.rb
UnknownError: An unknown server-side error occurred while processing the command. Original error: android.util.AndroidException: INSTRUMENTATION_FAILED: io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner: An unknown server-side error occurred while processing the command. Original error: android.util.AndroidException: INSTRUMENTATION_FAILED: io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner (Selenium::WebDriver::Error::UnknownError)
        from     at getResponseForW3CError (/Users/kazuaki/GitHub/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
        from     at asyncHandler (/Users/kazuaki/GitHub/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)
        from     at <anonymous>
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/appium_lib_core-2.3.1/lib/appium_lib_core/common/base/http_default.rb:33:in `call'
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/appium_lib_core-2.3.1/lib/appium_lib_core/common/base/bridge.rb:93:in `create_session'
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/appium_lib_core-2.3.1/lib/appium_lib_core/common/base/bridge.rb:33:in `handshake'
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/appium_lib_core-2.3.1/lib/appium_lib_core/common/base/driver.rb:20:in `initialize'
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/appium_lib_core-2.3.1/lib/appium_lib_core/driver.rb:242:in `new'
        from /Users/kazuaki/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/appium_lib_core-2.3.1/lib/appium_lib_core/driver.rb:242:in `start_driver'
        from test.rb:42:in `run_android_test'
        from test.rb:85:in `<main>'
```

**Comment by KazuCocoa** [comment]
https://github.com/KazuCocoa/flutter-appium/commit/027818206f15de1fbcbddef0757ed548acf9c4b1
https://github.com/KazuCocoa/flutter-appium/commit/f0af702d4cecb854afb5af7f175bc00e5646313e

**Comment by KazuCocoa** [comment]
checked.
